# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='textfield1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='textfield2',
        ),
    ]
