# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 16:25
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170310_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='markdownx_field3',
            field=markdownx.models.MarkdownxField(default=None),
            preserve_default=False,
        ),
    ]
