# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170310_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('markdownx_field1', markdownx.models.MarkdownxField()),
                ('markdownx_field2', markdownx.models.MarkdownxField(blank=True)),
                ('markdownx_field3', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
