# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170310_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownpage',
            name='base_url',
            field=models.CharField(max_length=50),
        ),
    ]
