# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170310_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdownpage',
            name='base_url',
        ),
        migrations.AddField(
            model_name='markdownpage',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
